require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/audit_records", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # AuditRecord. As you add validations to AuditRecord, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip("Add a hash of attributes valid for your model")
  end

  let(:invalid_attributes) do
    skip("Add a hash of attributes invalid for your model")
  end

  describe "GET /index" do
    it "renders a successful response" do
      AuditRecord.create! valid_attributes
      get audit_records_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      audit_record = AuditRecord.create! valid_attributes
      get audit_record_url(audit_record)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_audit_record_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      audit_record = AuditRecord.create! valid_attributes
      get edit_audit_record_url(audit_record)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new AuditRecord" do
        expect {
          post audit_records_url, params: { audit_record: valid_attributes }
        }.to change(AuditRecord, :count).by(1)
      end

      it "redirects to the created audit_record" do
        post audit_records_url, params: { audit_record: valid_attributes }
        expect(response).to redirect_to(audit_record_url(AuditRecord.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new AuditRecord" do
        expect {
          post audit_records_url, params: { audit_record: invalid_attributes }
        }.to change(AuditRecord, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post audit_records_url, params: { audit_record: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) do
        skip("Add a hash of attributes valid for your model")
      end

      it "updates the requested audit_record" do
        audit_record = AuditRecord.create! valid_attributes
        patch audit_record_url(audit_record), params: { audit_record: new_attributes }
        audit_record.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the audit_record" do
        audit_record = AuditRecord.create! valid_attributes
        patch audit_record_url(audit_record), params: { audit_record: new_attributes }
        audit_record.reload
        expect(response).to redirect_to(audit_record_url(audit_record))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        audit_record = AuditRecord.create! valid_attributes
        patch audit_record_url(audit_record), params: { audit_record: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested audit_record" do
      audit_record = AuditRecord.create! valid_attributes
      expect {
        delete audit_record_url(audit_record)
      }.to change(AuditRecord, :count).by(-1)
    end

    it "redirects to the audit_records list" do
      audit_record = AuditRecord.create! valid_attributes
      delete audit_record_url(audit_record)
      expect(response).to redirect_to(audit_records_url)
    end
  end
end
