require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/response_pages", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ResponsePage. As you add validations to ResponsePage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip("Add a hash of attributes valid for your model")
  end

  let(:invalid_attributes) do
    skip("Add a hash of attributes invalid for your model")
  end

  describe "GET /index" do
    it "renders a successful response" do
      ResponsePage.create! valid_attributes
      get response_pages_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      response_page = ResponsePage.create! valid_attributes
      get response_page_url(response_page)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_response_page_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      response_page = ResponsePage.create! valid_attributes
      get edit_response_page_url(response_page)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ResponsePage" do
        expect {
          post response_pages_url, params: { response_page: valid_attributes }
        }.to change(ResponsePage, :count).by(1)
      end

      it "redirects to the created response_page" do
        post response_pages_url, params: { response_page: valid_attributes }
        expect(response).to redirect_to(response_page_url(ResponsePage.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ResponsePage" do
        expect {
          post response_pages_url, params: { response_page: invalid_attributes }
        }.to change(ResponsePage, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post response_pages_url, params: { response_page: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) do
        skip("Add a hash of attributes valid for your model")
      end

      it "updates the requested response_page" do
        response_page = ResponsePage.create! valid_attributes
        patch response_page_url(response_page), params: { response_page: new_attributes }
        response_page.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the response_page" do
        response_page = ResponsePage.create! valid_attributes
        patch response_page_url(response_page), params: { response_page: new_attributes }
        response_page.reload
        expect(response).to redirect_to(response_page_url(response_page))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        response_page = ResponsePage.create! valid_attributes
        patch response_page_url(response_page), params: { response_page: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested response_page" do
      response_page = ResponsePage.create! valid_attributes
      expect {
        delete response_page_url(response_page)
      }.to change(ResponsePage, :count).by(-1)
    end

    it "redirects to the response_pages list" do
      response_page = ResponsePage.create! valid_attributes
      delete response_page_url(response_page)
      expect(response).to redirect_to(response_pages_url)
    end
  end
end
